### ISSUE TITLE
Including additional libraries

### ISSUE THREAD

**Issue by hazcod** [troian/golang-cross#4]
Hi @troian, first of all thank you for your work here!

I am trying to cross-compile a Go project (https://github.com/hazcod/ssh-ca-provider) but failing because it requires CGO to include `libpcsc`.

Usage:
```shell
% docker run -ti --rm -v $(pwd)/app --workdir /app troian/golang-cross build --rm-dist --snapshot --config=.github/goreleaser.yml
```

goreleaser.yml:
```yaml
before:
  hooks:
  - apt-get update && apt-get install -y pkgconf pcsc-lite-dev gcc libpcsclite-dev libpcsclite
  - go mod download

dockers:
-
  image_templates:
  - "ghcr.io/hazcod/ssh-ca-provider/sscp:{{ .Tag }}"
  - "ghcr.io/hazcod/ssh-ca-provider/sscp:v{{ .Major }}"
  - "ghcr.io/hazcod/ssh-ca-provider/sscp:latest"

builds:
-
  id: darwin-amd64
  dir: ./cmd/client/
  goos:
  - darwin
  goarch:
  - amd64
  env:
  - CGO_ENABLED=1
  - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
  - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
  - CC=o64-clang
  - CXX=o64-clang++
  flags:
  - -mod=readonly
  ldflags:
  - -s -w -X main.version={{.Version}}
-
  id: linux-armhf
  dir: ./cmd/client/
  goos:
  - linux
  goarch:
  - arm
  goarm:
  - 7
  env:
  - CGO_ENABLED=1
  - CC=arm-linux-gnueabihf-gcc
  - CXX=arm-linux-gnueabihf-g++
  - CGO_FLAGS=--sysroot=/sysroot/linux/armhf
  - CGO_LDFLAGS=--sysroot=/sysroot/linux/armhf
  - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/armhf
  - PKG_CONFIG_PATH=/sysroot/linux/armhf/opt/vc/lib/pkgconfig:/sysroot/linux/armhf/usr/lib/arm-linux-gnueabihf/pkgconfig:/sysroot/linux/armhf/usr/lib/pkgconfig:/sysroot/linux/armhf/usr/local/lib/pkgconfig
  flags:
  - -mod=readonly
  ldflags:
  - -s -w -X main.version={{.Version}}

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore'
```

And the logs:
```
   ⨯ build failed after 269.69s error=failed to build for linux_arm_7: # pkg-config --cflags  -- libpcsclite
Package libpcsclite was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpcsclite.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpcsclite' found
pkg-config: exit status 1

```
