### ISSUE TITLE
cgo: C compiler "x86_64-w64-mingw32-gcc" not found

### ISSUE THREAD

**Issue by pmoscode** [troian/golang-cross#5]
Hi troian,

I'm trying to cross-compile my go app for linux and windows, but in my pipeline I'm getting this:

```
release failed after 78.89s error=failed to build for windows_amd64: exit status 2: # runtime/cgo
cgo: C compiler "x86_64-w64-mingw32-gcc" not found: exec: "x86_64-w64-mingw32-gcc": executable file not found in $PATH
```

Using this command:

```
docker run --rm --privileged \
      -v $PWD:/go/src/gitlab.com/pmoscode/tarpit-analyzer \
      -w /go/src/gitlab.com/pmoscode/tarpit-analyzer \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e DOCKER_USERNAME -e DOCKER_PASSWORD -e DOCKER_REGISTRY  \
      -e GITLAB_TOKEN \
      -e CGO_ENABLED=1 \
      troian/golang-cross:v1.17.2-base release --rm-dist
```

I have neither sysroot nor --env-file .release-env set.

And this is my build section inside .goreleaser.yaml:
```
builds:
  - id: linux-amd64
    env:
      - CC=gcc
      - CXX=g++
    goos:
      - linux
    goarch:
      - amd64
  - id: windows-amd64
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
```

What have I missed?

Thx
